project_name: thousandeyes-sdk-go
release:
  github:
    owner: thousandeyes
    name: thousandeyes-sdk-go
  draft: false
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
builds:
  - id: "default"
    main: ./command/tectl/main.go
    binary: tectl
    ldflags:
      - -s -w -X main.build={{.Version}}
    goarch:
      - amd64
    goos:
      - windows
      - linux
      - darwin
